FROM ubuntu:bionic

LABEL maintainer="Lander Usategui <lander at erlerobotics dot com>"

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV TERM xterm
ENV ROS_DISTRO dashing
RUN \
    echo 'Etc/UTC' > /etc/timezone \
      && ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime \
      && apt-get update -qq && apt-get install -qq -y tzdata dirmngr gnupg2 lsb-release curl \
      # setup ros2 keys
      && curl http://repo.ros2.org/repos.key | apt-key add - \
      # setup sources.list
      && echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list \
      && apt-get update -qq && apt-get install -qq -y \
        build-essential \
        cmake \
        git \
        python3-colcon-common-extensions \
        python3-lark-parser \
        python3-lxml \
        python3-numpy \
        python3-pip \
        python-rosdep \
        python3-vcstool \
        wget \
        clang clang-format-3.9 clang-tidy clang-tools \
     && python3 -m pip install -U \
        argcomplete \
        flake8 \
        flake8-blind-except \
        flake8-builtins \
        flake8-class-newline \
        flake8-comprehensions \
        flake8-deprecated \
        flake8-docstrings \
        flake8-import-order \
        flake8-quotes \
        pytest-repeat \
        pytest-rerunfailures \
        pytest \
        pytest-cov \
        pytest-runner \
        setuptools \
    && apt install --no-install-recommends -y \
        libasio-dev \
        libtinyxml2-dev

RUN mkdir -p ~/ros2_ws/src \
    && cd ~/ros2_ws \
    && wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos \
    && vcs import src < ros2.repos \
    && apt-get -qq update \
    && rosdep init && \
    rosdep update -q && \
    rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 rti-connext-dds-5.3.1 urdfdom_headers" --as-root=apt:false || true \
    && rm -rf /var/lib/apt/lists/*

RUN cd ~/ros2_ws && colcon build --merge-install --install-base /opt/ros/dashing && cd ~ && rm -rf ros2_ws

CMD ["bash"]
